version: '3'
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: backend-api
    env_file:
      - .env
    ports:
      - "3333:3333"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=$kadu99
      - MONGO_INITDB_ROOT_PASSWORD=$kadu1995
      
    depends_on:
      - mongo
    networks:
      - aplicacao-network
    working_dir: /usr/src/app
    volumes:
      - .:/home/node/app

  mongo:
    image: mongo
    restart: always
    container_name: Mongo_BD
    ports:
      - "27017:27017"
    environment:
      - DB_HOST=mongodb
      - DB_USER=$MONGODB_USER
      - DB_PASSWORD=$MONGODB_PASSWORD
      - DB_NAME=$MONGODB_DATABASE
      - DB_PORT=$MONGODB_DOCKER_PORT
    
    networks:
      - aplicacao-network
          

networks:
  aplicacao-network:  
    name: "aplicacao-network"
    driver: bridge  

